// ============================================================
// QUIZ QUESTIONS — Organized by Professional Field
// ============================================================

export const QUIZ_CONFIG = {
  TIMER_MINUTES: 5,   // Change this to adjust quiz time
  TOTAL_MARKS_PER_QUESTION: 1,
};

export const WebDeveloperQuestions = [
  {
    id: 1,
    professional: "Web Development",
    question: "What does HTML stand for?",
    options: ["HyperText Markup Language", "HighText Machine Language", "HyperText and links Markup Language", "None of these"],
    answer: "HyperText Markup Language",
  },
  {
    id: 2,
    professional: "Web Development",
    question: "Which language is used for styling web pages?",
    options: ["HTML", "CSS", "JavaScript", "Python"],
    answer: "CSS",
  },
  {
    id: 3,
    professional: "Web Development",
    question: "What does CSS stand for?",
    options: ["Cascading Style Sheets", "Creative Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"],
    answer: "Cascading Style Sheets",
  },
  {
    id: 4,
    professional: "Web Development",
    question: "Inside which HTML element do we put JavaScript?",
    options: ["<js>", "<scripting>", "<script>", "<javascript>"],
    answer: "<script>",
  },
  {
    id: 5,
    professional: "Web Development",
    question: "What is the correct syntax for referring to an external script called 'app.js'?",
    options: ['<script href="app.js">', '<script src="app.js">', '<script name="app.js">', '<script file="app.js">'],
    answer: '<script src="app.js">',
  },
  {
    id: 6,
    professional: "Web Development",
    question: "Which of the following is NOT a JavaScript data type?",
    options: ["String", "Boolean", "Float", "Undefined"],
    answer: "Float",
  },
  {
    id: 7,
    professional: "Web Development",
    question: "How do you declare a JavaScript variable?",
    options: ["variable x;", "v x;", "var x;", "int x;"],
    answer: "var x;",
  },
  {
    id: 8,
    professional: "Web Development",
    question: "Which operator is used to assign a value to a variable?",
    options: ["*", "=", "-", "x"],
    answer: "=",
  },
  {
    id: 9,
    professional: "Web Development",
    question: "What will the following return: Boolean(10 > 9)?",
    options: ["true", "false", "NaN", "undefined"],
    answer: "true",
  },
  {
    id: 10,
    professional: "Web Development",
    question: "What is the correct way to write a JavaScript array?",
    options: ['var colors = "red", "green", "blue"', 'var colors = (1:"red", 2:"green", 3:"blue")', 'var colors = ["red", "green", "blue"]', 'var colors = {red, green, blue}'],
    answer: 'var colors = ["red", "green", "blue"]',
  },
  {
    id: 11,
    professional: "Web Development",
    question: "Which HTML attribute is used to define inline styles?",
    options: ["class", "font", "styles", "style"],
    answer: "style",
  },
  {
    id: 12,
    professional: "Web Development",
    question: "What does the 'z-index' CSS property control?",
    options: ["Zoom level", "Stacking order of elements", "Z-axis rotation", "Zigzag border"],
    answer: "Stacking order of elements",
  },
  {
    id: 13,
    professional: "Web Development",
    question: "What is React primarily used for?",
    options: ["Database Management", "Server-side scripting", "Building user interfaces", "Styling web pages"],
    answer: "Building user interfaces",
  },
  {
    id: 14,
    professional: "Web Development",
    question: "What is JSX?",
    options: ["A JavaScript framework", "A CSS preprocessor", "A syntax extension for JavaScript", "A database query language"],
    answer: "A syntax extension for JavaScript",
  },
  {
    id: 15,
    professional: "Web Development",
    question: "Which hook is used to manage state in React functional components?",
    options: ["useEffect", "useState", "useContext", "useRef"],
    answer: "useState",
  },
  {
    id: 16,
    professional: "Web Development",
    question: "What does the '===' operator check in JavaScript?",
    options: ["Value only", "Type only", "Value and type", "Neither"],
    answer: "Value and type",
  },
  {
    id: 17,
    professional: "Web Development",
    question: "What is the purpose of the 'useEffect' hook in React?",
    options: ["To manage state", "To handle side effects", "To create context", "To handle routing"],
    answer: "To handle side effects",
  },
  {
    id: 18,
    professional: "Web Development",
    question: "What does the CSS 'flexbox' property help with?",
    options: ["Animation", "Typography", "Flexible layout design", "Color schemes"],
    answer: "Flexible layout design",
  },
  {
    id: 19,
    professional: "Web Development",
    question: "Which HTML5 element is used to define navigation links?",
    options: ["<nav>", "<navigation>", "<navigate>", "<menu>"],
    answer: "<nav>",
  },
  {
    id: 20,
    professional: "Web Development",
    question: "What is the use of localStorage in browsers?",
    options: ["Storing data on the server", "Storing session cookies", "Storing data in the browser persistently", "Caching images"],
    answer: "Storing data in the browser persistently",
  },
  {
    id: 21,
    professional: "Web Development",
    question: "What is the purpose of 'props' in React?",
    options: ["State management", "Passing data to components", "Styling components", "Routing between pages"],
    answer: "Passing data to components",
  },
  {
    id: 22,
    professional: "Web Development",
    question: "Which method converts a JSON string to a JavaScript object?",
    options: ["JSON.parse()", "JSON.stringify()", "JSON.convert()", "JSON.toObject()"],
    answer: "JSON.parse()",
  },
  {
    id: 23,
    professional: "Web Development",
    question: "Which method converts a JavaScript object to a JSON string?",
    options: ["JSON.parse()", "JSON.stringify()", "JSON.serialize()", "JSON.format()"],
    answer: "JSON.stringify()",
  },
  {
    id: 24,
    professional: "Web Development",
    question: "What does 'DOM' stand for in web development?",
    options: ["Document Object Model", "Data Object Management", "Dynamic Output Module", "Document Output Model"],
    answer: "Document Object Model",
  },
  {
    id: 25,
    professional: "Web Development",
    question: "Which CSS framework uses utility-first classes?",
    options: ["Bootstrap", "Bulma", "Tailwind CSS", "Foundation"],
    answer: "Tailwind CSS",
  },
];

export const UiUxQuestions = [
  {
    id: 101,
    professional: "UI UX",
    question: "What does UX stand for?",
    options: ["User eXperience", "Unique eXperience", "User Extension", "Ultra eXperience"],
    answer: "User eXperience",
  },
  {
    id: 102,
    professional: "UI UX",
    question: "What is the primary goal of UX design?",
    options: ["To make things pretty", "To create a good user experience", "To use many colors", "To complicate interfaces"],
    answer: "To create a good user experience",
  },
  {
    id: 103,
    professional: "UI UX",
    question: "What does UI stand for?",
    options: ["User Interface", "Unique Interface", "Universal Interface", "User Interaction"],
    answer: "User Interface",
  },
  {
    id: 104,
    professional: "UI UX",
    question: "Which of these is NOT a principle of good UI design?",
    options: ["Consistency", "Simplicity", "Complexity", "Clarity"],
    answer: "Complexity",
  },
  {
    id: 105,
    professional: "UI UX",
    question: "What is wireframing?",
    options: ["A design tool", "A low-fidelity layout of a website", "A programming language", "A color palette"],
    answer: "A low-fidelity layout of a website",
  },
  {
    id: 106,
    professional: "UI UX",
    question: "What is the purpose of user research in UX design?",
    options: ["To make designs beautiful", "To understand user needs and behaviors", "To speed up design process", "To reduce costs"],
    answer: "To understand user needs and behaviors",
  },
  {
    id: 107,
    professional: "UI UX",
    question: "What does 'prototyping' mean in UI/UX design?",
    options: ["Final product", "Creating an interactive mockup", "Writing code", "Testing stage"],
    answer: "Creating an interactive mockup",
  },
  {
    id: 108,
    professional: "UI UX",
    question: "Which tool is commonly used for UI/UX design?",
    options: ["Visual Studio Code", "Figma", "MongoDB", "Express"],
    answer: "Figma",
  },
  {
    id: 109,
    professional: "UI UX",
    question: "What is 'user empathy' in UX design?",
    options: ["Liking the user", "Understanding and feeling user emotions", "Marketing", "Selling products"],
    answer: "Understanding and feeling user emotions",
  },
  {
    id: 110,
    professional: "UI UX",
    question: "What is an 'information architecture' in UX?",
    options: ["Building structure", "Organizing and structuring information", "Database design", "Server architecture"],
    answer: "Organizing and structuring information",
  },
  {
    id: 111,
    professional: "UI UX",
    question: "What is 'accessibility' in UI/UX design?",
    options: ["Easy to find", "Designing for people of all abilities", "Making things cheap", "Fast loading"],
    answer: "Designing for people of all abilities",
  },
  {
    id: 112,
    professional: "UI UX",
    question: "What does 'white space' do in UI design?",
    options: ["It's wasted space", "Improves readability and reduces clutter", "Increases file size", "Slows down loading"],
    answer: "Improves readability and reduces clutter",
  },
  {
    id: 113,
    professional: "UI UX",
    question: "What is 'color theory' in UI design?",
    options: ["Art history", "Study of colors and their relationships", "Painting techniques", "Photography"],
    answer: "Study of colors and their relationships",
  },
  {
    id: 114,
    professional: "UI UX",
    question: "What is a 'user persona'?",
    options: ["A real user", "Fictional representation of target user", "Job title", "Username"],
    answer: "Fictional representation of target user",
  },
  {
    id: 115,
    professional: "UI UX",
    question: "What is 'usability testing'?",
    options: ["Testing code", "Getting feedback from actual users", "Beta testing", "QA testing"],
    answer: "Getting feedback from actual users",
  },
  {
    id: 116,
    professional: "UI UX",
    question: "What does 'responsive design' mean?",
    options: ["Fast page loading", "UI adapts to different screen sizes", "Server-side rendering", "Interactive design"],
    answer: "UI adapts to different screen sizes",
  },
  {
    id: 117,
    professional: "UI UX",
    question: "What is 'interaction design'?",
    options: ["Physical interaction", "Designing how users interact with products", "Social media", "Customer service"],
    answer: "Designing how users interact with products",
  },
  {
    id: 118,
    professional: "UI UX",
    question: "What is a 'design system'?",
    options: ["Operating system", "Organized set of design guidelines and components", "Design tool", "File system"],
    answer: "Organized set of design guidelines and components",
  },
  {
    id: 119,
    professional: "UI UX",
    question: "What is 'call to action (CTA)' in UI design?",
    options: ["Customer service", "Button prompting user to do something", "Phone number", "Email address"],
    answer: "Button prompting user to do something",
  },
  {
    id: 120,
    professional: "UI UX",
    question: "What is 'heuristic evaluation' in UX?",
    options: ["User testing", "Expert review using established principles", "Algorithm", "Machine learning"],
    answer: "Expert review using established principles",
  },
];

// Combine all questions based on professional field
export const ALL_QUESTIONS = [...WebDeveloperQuestions, ...UiUxQuestions];
 